### ISSUE TITLE
daemonization failure

### ISSUE THREAD

**Issue by hussainmkj** [chrys87/fenrir#11]
Get the following error when running as root after installation:

    Traceback (most recent call last):
      File "/usr/bin/fenrir", line 26, in <module>
        daemon = Daemonize(app="fenrir-daemon", pid=pidFile, action=main, chdir=os.path.dirname(os.path.realpath(__main__.__file__)))
    TypeError: __init__() got an unexpected keyword argument 'chdir'

**Comment by manuelcortez** [comment]
Can you provide more information please? What system are you using? How did you installed python-daemonize? (package manager or through PIP) and what's your current python version?

**Comment by chrys87** [comment]
This one here is needed:
https://pypi.python.org/pypi/daemonize/

**Comment by hussainmkj** [comment]
Daemonize 2.4.7 installed through pip.

Python v 3.5.2

**Comment by chrys87** [comment]
seems to be ok. it does somehow not recognize the optional paramter in __init__.
What opperating system are you using?
what do you get by
sudo python -v /usr/bin/fenrir

can you send me the file 
/usr/lib/python<YOUR VERSION>/site-packages/daemonize.py
or can you take a look if 
chdir="/" is defined there in __init__?

cheers chrys

**Comment by hussainmkj** [comment]
Ahh, I figured out the issue; there seems to have been a pre-existing older debian install of daemonize.

Sorry for the trouble.

**Comment by chrys87** [comment]
you are welcome. 
if you need any other help just let me know.
fenrir is very young and envolves fast. so if something does not work like expected, just tell.
