### ISSUE TITLE
Incoherency for /usr/bin/fenrir or fenrir-daemon

### ISSUE THREAD

**Issue by sthibaul** [chrys87/fenrir#13]
Hello,

install.sh links fenrir-daemon into /usr/bin/fenrir, but ./autostart/systemd/fenrir.service execs /usr/bin/fenrir-daemon , that can't work.

**Comment by chrys87** [comment]
i cannot see that
ln -fs /opt/fenrir/fenrir-daemon /usr/bin/fenrir-daemon
ln -fs /opt/fenrir/fenrir /usr/bin/fenrir

links "fenrir" into "fenrir and "fenrir-daemon" into "fenrir-daemon"

**Comment by sthibaul** [comment]
I was looking at the latest releases: 1.05 and 1.06

**Comment by sthibaul** [comment]
It seems to be fixed in 1.5
