### ISSUE TITLE
configure-pulseaudio script not actually installed

### ISSUE THREAD

**Issue by sthibaul** [chrys87/fenrir#14]
Hello,

install.sh advises the user to use /usr/share/fenrir/tools/configure-pulseaudio , but this is actually not installed by install.sh

**Comment by chrys87** [comment]
Howdy,

the following lines are copieng all tools (also configure-pulse.sh)
install -m755 -d /usr/share/fenrir/tools
cp -af tools/* /usr/share/fenrir/tools

could it be that you are using an old version of fenrir, where all that stuff was not fixed yet?
i recomment installing current fenrir versions via setup.py thats the "offical" python way of love :).

**Comment by sthibaul** [comment]
I was looking at the latest releases 1.05 and 1.06

**Comment by sthibaul** [comment]
One usually looks at released versions, not what happens to be the tip of the development tree, which could be at an unknown stability state.

**Comment by chrys87** [comment]
Howdy,

the latest release is fresh 1.5 (just 2 weeks old) not 1.0x.
i create a tarball to reduce confusion (it was currently just living in git :),  )
https://github.com/chrys87/fenrir/releases/tag/1.5.0

**Comment by sthibaul** [comment]
Just creating a tag in the git tree is not enough to make it known indeed.
Thanks for the tarball, I'll package it.

**Comment by chrys87** [comment]
I m sorry :),
i try to improve myself in version management.
Back to the problem: fixed in 1.5 branch right?

**Comment by sthibaul** [comment]
the tool is installed, yes, just not with the same name: install.sh talks about configure-pulseaudio, while the tool is called configure_pulse.sh

**Comment by chrys87** [comment]
I changed the install.sh to print the correct scriptname
"configure_pulse.sh"
and did a bugfix release for you
https://github.com/chrys87/fenrir/archive/1.5.1.tar.gz
thanks testing + reporting :).
any reported and fixed bug can only improve fenrirs quality.

**Comment by chrys87** [comment]
is this fixed?

**Comment by sthibaul** [comment]
Yes it seems to be
