### ISSUE TITLE
version 1.9.3 does not start due to syntax error in version variable

### ISSUE THREAD

**Issue by sthibaul** [chrys87/fenrir#44]
When starting fenrir 1.9.3, we get

      File "/usr/lib/python3/dist-packages/fenrirscreenreader/fenrirVersion.py", line 7
        version = 1.9.3
                      ^
    SyntaxError: invalid syntax

This is indeed invalid python. Perhaps a string was intended here?

**Comment by chrys87** [comment]
You are completely right.
I wonder why it starts here because it shouldnt.
i fix it and release an 1.9.4.

**Comment by chrys87** [comment]
Fixed
I released 1.9.4 to fix it.
