### ISSUE TITLE
Failed to start fenrir.service: Unit fenrir.service not found.

### ISSUE THREAD

**Issue by CaptainQuirk** [chrys87/fenrir#49]
Hi !

I just wanted to try **fenrir** out. Unfortunately, after downloading, making `install.sh` executable and launching it I get the aforementioned error.

What did I do wrong ?

Thanks in advance !

**Comment by stormdragon2976** [comment]
To stop Fenrir from conflicting with other software, we named the service file fenrirscreenreader.service. So, try sudo systemctl start fenrirscreenreader.service. This is assuming you are running the Arch Linux version of the package.
You can also run Fenrir without  systemd if you prefer, to do so, use sudo fenrir-daemon.

**Comment by CaptainQuirk** [comment]
I'm on Ubuntu 16.04.

Changing the name of the service won't do. Still get the same error.

Using **fenrir-daemon** with `sudo src/fenrir-daemon` yields the following error : 

```
Traceback (most recent call last):
  File "src/fenrir-daemon", line 26, in <module>
    daemon = Daemonize(app="fenrir-daemon", pid=pidFile, action=main, chdir=fenrirPath)
TypeError: __init__() got an unexpected keyword argument 'chdir'
```

**Comment by stormdragon2976** [comment]
Sorry for taking so long to get back to you. The problem seems to be out of date Ubuntu packages. You could try installing fenrir-screenreader with pip, but this could break other python dependancies.
Fenrir is packaged in Ubuntu 18.04, so if upgrading is an option, you could get it from that.

**Comment by CaptainQuirk** [comment]
Thanks for your answer !

**Comment by chrys87** [comment]
To be more complete:
fenrir requires python3-daemonize 2.4.7
ubuntu 16.04 only ships 2.3.1.
