### ISSUE TITLE
fenrir and archiso with anarchy problem when booting up

### ISSUE THREAD

**Issue by stas-prze** [chrys87/fenrir#56]
I am working with anarchy developers to add accessibility to theyr installer.
At first i used espeakup, but when i would want to install a desktop it would conflict with orca.
I downloaded the aur fenrir package, edited a pkgbuild a little to provide some optional depends as required, made python-espeak from aur too, and created an arch repository with these packages at
https://stas-prze.github.io/arch/repo
I edited the customize-airootfs.sh to start fenrir as a system service, and it worked perfectly.
The problem is when i start the iso.
I cant tell you what exactly fenrir says because of the startup sound beeing a little to loud, but i hear that it starts with that 8bitty dingdong, and then i hear something is not installed, something is a name of some package or something like that, i thing something related to speech.
I also switched my repo out for the jenux repo, and tested with that and the jenux fenrir config, but it didn't work, even no startup sound and no speech, unless speech dispatcher didn't installwhitch it should have cause i didn't hear any error of sord failed to enable speech-dispatcherd.service.
If you want i can send over my archiso config

**Comment by alex19EP** [comment]
hello. current espeak don't conflict with espeak-ng. so you can use espeakup. if you want.

**Comment by stas-prze** [comment]
oh i see now.
On manjaro when i tried for some reason it did conflict.
So i guess i'm sticking with espeakup atleast for now.

**Comment by chrys87** [comment]
The notification you hear is maybe only the notice that the spellchecker dependency is missing but the spellchecker is active.

The python package is called „pyenchant“

https://pypi.org/project/pyenchant/

By the way fenrir doesnt requre python-espeak, the generic speech driver is very fast :). it also doesnt care about espeak or espeak-ng.

Let me know when i can help. Maybe you can provide an debug file for me to figures issueas?



Cheers chrys

**Comment by chrys87** [comment]
> hello. current espeak don't conflict with espeak-ng. so you can use espeakup. if you want.

**Comment by chrys87** [comment]
> hello. current espeak don't conflict with espeak-ng. so you can use espeakup. if you want.

Howdy,

Sorry i do disagree with the way of commenting. This is fenrirs issue page. If there are bug, they should get fixed instead of being ignored.  and this is IMO not only true in this case.

**Comment by alex19EP** [comment]
ok. @chrys87  i just wanted to help. I hope you are not offended.
