### ISSUE TITLE
System freezes after login

### ISSUE THREAD

**Issue by RetroBunn** [chrys87/fenrir#67]
Hello,
I recently installed fenrir-git from the AUR. After login, the system freezes when Fenrir is first loaded when the system is set to use SpeechDispatcher as my output module of choice.

Here is what I did before installation:

- Grant ReadWrite permission to /dev/input and /dev/uinput
- Grant Read permission to /sys/devices/virtual/tty/tty0/active, /dev/tty1, and /dev/vcsa1
- Install sox for sound output
- SpeechDispatcher is working as expected with voxin output module.

After installation, I ran the configure_pipewire script as both root and as my regular user. Pipewire and pipewire-pulse are set to start at boot, and my regular user is also added to the "audio" group.

When rebooting the system and logging in with my username and password, the system locks up and freezes after a few seconds. Sometimes, I do hear the Fenrir startup sound, but other times, I don't.

Is there anything I'm doing wrong, or is there a step I'm missing?

Thanks.

**Comment by stormdragon2976** [comment]
Enable linger for your user:

sudo loginctl enable-linger

This will make pipewire start for you at login, and Fenrir will be able
to access it.

**Comment by RetroBunn** [comment]
> Enable linger for your user:
> 
> sudo loginctl enable-linger
> 
> This will make pipewire start for you at login, and Fenrir will be able
> to access it.
> 

I just tried this earlier this morning and it does appear to work now, and my system no longer freezes and locks up on boot!
Thanks so much for your help!
